
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const OPEN_EDIT_PROJECT = 'OPEN_EDIT_PROJECT';
export const CLOSE_EDIT_PROJECT = 'CLOSE_EDIT_PROJECT';
export const SUBMIT_PROJECT = 'SUBMIT_PROJECT';
export const IS_LOADING = 'IS_LOADING';
export const EDIT_PROJECT = 'EDIT_PROJECT';